# -*- coding: utf-8 -*-
"""PYTHON  ASSIGNMENT1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZA7NH_URKp1WF0MecVOj-4zMtTDOa6z
"""

#program to design a simple calculator for the operators
a=8
b=6
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a/b)
print(a//b)
print(a%b)

#program to calculate simple interest
p=30
q=6
r=67
SI=(p*q*r)/100
print(SI)

#program to calculate area of a circle
r=6
radius=3.14*r*r
print(radius)

#program to calculate area of triangle
b=10
h=10
print(1/2*b*h)

#program to temperature in celsius to fahrenheit
Celsius=50
Fahrenheit=(1.8*Celsius)+32
print(Fahrenheit)

#program to calculate area of rectangle
l=float(input('enter the length'))
b=float(input('enter the breadth'))
area=l*b
print(l*b)

#program to calculate perimeter of square
a=float(input('enter the value of a'))
perimeter=4*a
print(perimeter)

#program to calculate circumference of a circle
r=float(input('enter the radius'))
circumference=2*3.14*r
print(circumference)

#program to calculate swap two numbers
x=int(input('enter the value of x'))
y=int(input('enter the value of y'))
temp,x=x,y
y=temp
print(x,y)



"""Assignment 
        By (Tinnelapudi Rakesh Kumar)
"""